"""
Export Functionality Components
Implements TXT and Markdown export functionality
"""

from typing import Dict, Any, Optional
from datetime import datetime
import streamlit as st
from utils.ui_helpers import format_currency


def create_export_filename(destination: str, format_type: str = "txt") -> str:
    """
    Create a standardized filename for itinerary exports.
    
    Args:
        destination: Travel destination
        format_type: Export format (txt, md)
    
    Returns:
        Sanitized filename
    """
    safe_destination = "".join(c for c in destination if c.isalnum() or c in (' ', '-')).strip().replace(' ', '_')
    date_str = datetime.now().strftime('%Y%m%d')
    return f"itinerary_{safe_destination}_{date_str}.{format_type}"


def export_to_txt(itinerary: str, destination: str, days: int, budget: float, 
                  currency: str) -> bytes:
    """
    Export itinerary to plain text format.
    
    Args:
        itinerary: The full itinerary text
        destination: Travel destination
        days: Number of days
        budget: Total budget
        currency: Currency code
    
    Returns:
        Text content as bytes
    """
    header = f"""
================================================================================
                    AGENTIC TRAVEL ITINERARY PLANNER
                    Professional Travel Plan Export
================================================================================

Destination: {destination}
Duration: {days} day{'s' if days > 1 else ''}
Total Budget: {format_currency(budget, currency)}
Export Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

================================================================================
                            ITINERARY CONTENT
================================================================================

"""
    
    footer = f"""

================================================================================
                            END OF ITINERARY
================================================================================
Generated by Agentic Travel Itinerary Planner
Professional travel planning powered by AI
"""
    
    content = header + itinerary + footer
    return content.encode('utf-8')


def export_to_markdown(itinerary: str, destination: str, days: int, budget: float,
                       currency: str) -> bytes:
    """
    Export itinerary to Markdown format.
    
    Args:
        itinerary: The full itinerary text
        destination: Travel destination
        days: Number of days
        budget: Total budget
        currency: Currency code
    
    Returns:
        Markdown content as bytes
    """
    header = f"""# {destination} Travel Itinerary

**Duration:** {days} day{'s' if days > 1 else ''}  
**Total Budget:** {format_currency(budget, currency)}  
**Export Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

"""
    
    footer = f"""

---

*Generated by Agentic Travel Itinerary Planner*  
*Professional travel planning powered by AI*
"""
    
    content = header + itinerary + footer
    return content.encode('utf-8')


def get_export_formats() -> list:
    """Return list of available export formats."""
    return ['txt', 'md']
