"""
Export Functionality Components
Implements TXT, PDF, and Markdown export functionality
"""

from typing import Dict, Any, Optional
from datetime import datetime
import os
import tempfile
import base64
import streamlit as st
from utils.ui_helpers import format_currency


def create_export_filename(destination: str, format_type: str = "txt") -> str:
    """
    Create a standardized filename for itinerary exports.
    
    Args:
        destination: Travel destination
        format_type: Export format (txt, pdf, md)
    
    Returns:
        Sanitized filename
    """
    safe_destination = "".join(c for c in destination if c.isalnum() or c in (' ', '-')).strip().replace(' ', '_')
    date_str = datetime.now().strftime('%Y%m%d')
    return f"itinerary_{safe_destination}_{date_str}.{format_type}"


def export_to_txt(itinerary: str, destination: str, days: int, budget: float, 
                  currency: str) -> bytes:
    """
    Export itinerary to plain text format.
    
    Args:
        itinerary: The full itinerary text
        destination: Travel destination
        days: Number of days
        budget: Total budget
        currency: Currency code
    
    Returns:
        Text content as bytes
    """
    header = f"""
================================================================================
                    AGENTIC TRAVEL ITINERARY PLANNER
                    Professional Travel Plan Export
================================================================================

Destination: {destination}
Duration: {days} day{'s' if days > 1 else ''}
Total Budget: {format_currency(budget, currency)}
Export Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

================================================================================
                            ITINERARY CONTENT
================================================================================

"""
    
    footer = f"""

================================================================================
                            END OF ITINERARY
================================================================================
Generated by Agentic Travel Itinerary Planner
Professional travel planning powered by AI
"""
    
    content = header + itinerary + footer
    return content.encode('utf-8')


def export_to_markdown(itinerary: str, destination: str, days: int, budget: float,
                       currency: str) -> bytes:
    """
    Export itinerary to Markdown format.
    
    Args:
        itinerary: The full itinerary text
        destination: Travel destination
        days: Number of days
        budget: Total budget
        currency: Currency code
    
    Returns:
        Markdown content as bytes
    """
    header = f"""# {destination} Travel Itinerary

**Duration:** {days} day{'s' if days > 1 else ''}  
**Total Budget:** {format_currency(budget, currency)}  
**Export Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

"""
    
    footer = f"""

---

*Generated by Agentic Travel Itinerary Planner*  
*Professional travel planning powered by AI*
"""
    
    content = header + itinerary + footer
    return content.encode('utf-8')


def export_to_pdf(itinerary: str, destination: str, days: int, budget: float,
                  currency: str, budget_info: Optional[Dict[str, Any]] = None,
                  weather_info: Optional[Dict[str, Any]] = None) -> bytes:
    """
    Export itinerary to professionally formatted PDF with company branding.
    
    Args:
        itinerary: The full itinerary text
        destination: Travel destination
        days: Number of days
        budget: Total budget
        currency: Currency code
        budget_info: Optional budget breakdown information
        weather_info: Optional weather information
    
    Returns:
        PDF content as bytes (base64 encoded for Streamlit download)
    """
    try:
        # Try to import PDF generation libraries
        try:
            from reportlab.lib import colors
            from reportlab.lib.pagesizes import letter, A4
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.pdfgen import canvas
            from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
            HAS_REPORTLAB = True
        except ImportError:
            HAS_REPORTLAB = False
        
        if not HAS_REPORTLAB:
            # Fallback: Create HTML that can be printed to PDF
            return _export_to_pdf_html(itinerary, destination, days, budget, 
                                       currency, budget_info, weather_info)
        
        # Create PDF using ReportLab
        buffer = tempfile.NamedTemporaryFile(suffix='.pdf', delete=False)
        buffer.close()
        
        doc = SimpleDocTemplate(
            buffer.name,
            pagesize=letter,
            rightMargin=0.5*inch,
            leftMargin=0.5*inch,
            topMargin=0.5*inch,
            bottomMargin=0.5*inch
        )
        
        # Define styles
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.Color(0.118, 0.227, 0.373),  # #1E3A5F
            alignment=TA_CENTER,
            spaceAfter=30
        )
        
        subtitle_style = ParagraphStyle(
            'CustomSubtitle',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.Color(0.0, 0.502, 0.502),  # #008080
            alignment=TA_CENTER,
            spaceAfter=20
        )
        
        header_style = ParagraphStyle(
            'CustomHeader',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.Color(0.118, 0.227, 0.373),
            spaceAfter=10,
            spaceBefore=20
        )
        
        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['BodyText'],
            fontSize=11,
            leading=14,
            spaceAfter=10
        )
        
        # Build PDF content
        story = []
        
        # Header
        story.append(Paragraph("Agentic Travel Itinerary Planner", title_style))
        story.append(Paragraph("Professional Travel Plan", subtitle_style))
        story.append(Spacer(1, 0.5*inch))
        
        # Trip Information
        story.append(Paragraph("Trip Information", header_style))
        
        trip_data = [
            ['Destination:', destination],
            ['Duration:', f"{days} day{'s' if days > 1 else ''}"],
            ['Total Budget:', format_currency(budget, currency)],
            ['Export Date:', datetime.now().strftime('%Y-%m-%d %H:%M:%S')]
        ]
        
        trip_table = Table(trip_data, colWidths=[1.5*inch, 4*inch])
        trip_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(trip_table)
        story.append(Spacer(1, 0.25*inch))
        
        # Budget Summary (if available)
        if budget_info:
            story.append(Paragraph("Budget Summary", header_style))
            
            breakdown = budget_info.get('breakdown', {})
            if breakdown:
                budget_data = [['Category', 'Amount']]
                for cat, amt in list(breakdown.items())[:5]:
                    budget_data.append([cat.capitalize(), format_currency(amt, currency)])
                
                budget_table = Table(budget_data, colWidths=[2.5*inch, 2.5*inch])
                budget_table.setStyle(TableStyle([
                    ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 10),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                    ('TOPPADDING', (0, 0), (-1, -1), 6),
                    ('BACKGROUND', (0, 0), (0, 0), colors.Color(0.118, 0.227, 0.373)),
                    ('TEXTCOLOR', (0, 0), (0, 0), colors.white),
                ]))
                story.append(budget_table)
                story.append(Spacer(1, 0.25*inch))
        
        # Weather Summary (if available)
        if weather_info:
            forecast = weather_info.get('forecast', [])
            if forecast:
                story.append(Paragraph("Weather Forecast", header_style))
                
                weather_data = [['Date', 'Condition', 'Temperature']]
                for day in forecast[:5]:
                    weather_data.append([
                        day.get('date', 'N/A'),
                        day.get('condition', 'N/A'),
                        f"{day.get('temp', 'N/A')}°C"
                    ])
                
                weather_table = Table(weather_data, colWidths=[1.5*inch, 2*inch, 1.5*inch])
                weather_table.setStyle(TableStyle([
                    ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 9),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                    ('TOPPADDING', (0, 0), (-1, -1), 6),
                ]))
                story.append(weather_table)
                story.append(Spacer(1, 0.25*inch))
        
        # Itinerary Content
        story.append(Paragraph("Detailed Itinerary", header_style))
        
        # Split itinerary into paragraphs and add to story
        paragraphs = itinerary.split('\n\n')
        for para in paragraphs[:20]:  # Limit to first 20 paragraphs for PDF
            if para.strip():
                story.append(Paragraph(para.strip(), body_style))
        
        if len(paragraphs) > 20:
            story.append(Paragraph("[... Itinerary continues in full version ...]", body_style))
        
        story.append(Spacer(1, 0.5*inch))
        
        # Footer
        footer_text = "Generated by Agentic Travel Itinerary Planner | Professional travel planning powered by AI"
        story.append(Paragraph(footer_text, ParagraphStyle(
            'Footer',
            parent=styles['BodyText'],
            fontSize=9,
            textColor=colors.grey,
            alignment=TA_CENTER
        )))
        
        # Build PDF
        doc.build(story)
        
        # Read PDF content
        with open(buffer.name, 'rb') as f:
            pdf_content = f.read()
        
        # Clean up
        os.unlink(buffer.name)
        
        return pdf_content
        
    except Exception as e:
        print(f"PDF export error: {e}")
        # Fallback to HTML
        return _export_to_pdf_html(itinerary, destination, days, budget, 
                                   currency, budget_info, weather_info)


def _export_to_pdf_html(itinerary: str, destination: str, days: int, budget: float,
                        currency: str, budget_info: Optional[Dict[str, Any]] = None,
                        weather_info: Optional[Dict[str, Any]] = None) -> bytes:
    """
    Fallback HTML export for PDF generation when ReportLab is not available.
    """
    html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{destination} Travel Itinerary</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
        
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: 'Inter', sans-serif;
            line-height: 1.6;
            color: #1F2937;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px;
            background: white;
        }}
        
        .header {{
            text-align: center;
            border-bottom: 3px solid #1E3A5F;
            padding-bottom: 30px;
            margin-bottom: 40px;
        }}
        
        .header h1 {{
            color: #1E3A5F;
            font-size: 24px;
            margin-bottom: 10px;
        }}
        
        .header h2 {{
            color: #008080;
            font-size: 14px;
            font-weight: 500;
        }}
        
        .trip-info {{
            background: #F8F9FA;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 30px;
        }}
        
        .trip-info h3 {{
            color: #1E3A5F;
            margin-bottom: 15px;
            font-size: 16px;
        }}
        
        .info-grid {{
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 15px;
        }}
        
        .info-item {{
            display: flex;
            justify-content: space-between;
        }}
        
        .info-item span:first-child {{
            font-weight: 600;
            color: #1E3A5F;
        }}
        
        .info-item span:last-child {{
            color: #6B7280;
        }}
        
        .section {{
            margin-bottom: 30px;
        }}
        
        .section h3 {{
            color: #1E3A5F;
            font-size: 16px;
            margin-bottom: 15px;
            padding-bottom: 8px;
            border-bottom: 2px solid #E5E7EB;
        }}
        
        .budget-table {{
            width: 100%;
            border-collapse: collapse;
        }}
        
        .budget-table th {{
            background: #1E3A5F;
            color: white;
            padding: 10px;
            text-align: left;
            font-weight: 600;
        }}
        
        .budget-table td {{
            padding: 10px;
            border-bottom: 1px solid #E5E7EB;
        }}
        
        .budget-table tr:hover {{
            background: #F3F4F6;
        }}
        
        .weather-table {{
            width: 100%;
            border-collapse: collapse;
        }}
        
        .weather-table th {{
            background: #008080;
            color: white;
            padding: 10px;
            text-align: left;
            font-weight: 600;
        }}
        
        .weather-table td {{
            padding: 10px;
            border-bottom: 1px solid #E5E7EB;
        }}
        
        .itinerary-content {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            border: 1px solid #E5E7EB;
        }}
        
        .itinerary-content p {{
            margin-bottom: 15px;
            text-align: justify;
        }}
        
        .footer {{
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #E5E7EB;
            color: #9CA3AF;
            font-size: 12px;
        }}
        
        @media print {{
            body {{
                padding: 20px;
            }}
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Agentic Travel Itinerary Planner</h1>
        <h2>Professional Travel Plan</h2>
    </div>
    
    <div class="trip-info">
        <h3>Trip Information</h3>
        <div class="info-grid">
            <div class="info-item">
                <span>Destination:</span>
                <span>{destination}</span>
            </div>
            <div class="info-item">
                <span>Duration:</span>
                <span>{days} day{'s' if days > 1 else ''}</span>
            </div>
            <div class="info-item">
                <span>Total Budget:</span>
                <span>{format_currency(budget, currency)}</span>
            </div>
            <div class="info-item">
                <span>Export Date:</span>
                <span>{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</span>
            </div>
        </div>
    </div>
"""
    
    if budget_info:
        breakdown = budget_info.get('breakdown', {})
        if breakdown:
            html += """
    <div class="section">
        <h3>Budget Summary</h3>
        <table class="budget-table">
            <thead>
                <tr>
                    <th>Category</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
"""
            for cat, amt in list(breakdown.items())[:5]:
                html += f"""
                <tr>
                    <td>{cat.capitalize()}</td>
                    <td>{format_currency(amt, currency)}</td>
                </tr>
"""
            html += """
            </tbody>
        </table>
    </div>
"""
    
    if weather_info:
        forecast = weather_info.get('forecast', [])
        if forecast:
            html += """
    <div class="section">
        <h3>Weather Forecast</h3>
        <table class="weather-table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Condition</th>
                    <th>Temperature</th>
                </tr>
            </thead>
            <tbody>
"""
            for day in forecast[:5]:
                html += f"""
                <tr>
                    <td>{day.get('date', 'N/A')}</td>
                    <td>{day.get('condition', 'N/A')}</td>
                    <td>{day.get('temp', 'N/A')}°C</td>
                </tr>
"""
            html += """
            </tbody>
        </table>
    </div>
"""
    
    html += """
    <div class="section">
        <h3>Detailed Itinerary</h3>
        <div class="itinerary-content">
"""
    
    # Split and add paragraphs
    paragraphs = itinerary.split('\n\n')
    for para in paragraphs[:20]:
        if para.strip():
            html += f"<p>{para.strip()}</p>"
    
    if len(paragraphs) > 20:
        html += "<p><em>[... Itinerary continues in full version ...]</em></p>"
    
    html += """
        </div>
    </div>
    
    <div class="footer">
        Generated by Agentic Travel Itinerary Planner<br>
        Professional travel planning powered by AI
    </div>
</body>
</html>
"""
    
    return html.encode('utf-8')


def get_export_formats() -> list:
    """Return list of available export formats."""
    return ['txt', 'pdf', 'md']


def is_pdf_available() -> bool:
    """Check if PDF export is available (ReportLab installed)."""
    try:
        import reportlab
        return True
    except ImportError:
        return False
