"""
Sharing Functionality Components
Implements copy to clipboard, email sharing, and shareable link generation
"""

from typing import Dict, Any, Optional
from datetime import datetime, timedelta
import hashlib
import json
import streamlit as st
import streamlit.components.v1 as components
from components.analytics import track_share_event as _track_share_event


def copy_to_clipboard(text: str, success_message: str = "Copied to clipboard!") -> bool:
    """
    Copy text to clipboard with confirmation toast.
    
    Args:
        text: Text to copy to clipboard
        success_message: Message to display on success
    
    Returns:
        True if copy was successful
    """
    if not text:
        return False
    
    # Create unique ID for this copy operation
    copy_id = f"copy_{hashlib.md5(text.encode()).hexdigest()[:8]}"
    
    # Store text in session state for JavaScript access
    st.session_state[copy_id] = text
    
    # JavaScript to copy to clipboard
    escaped_text = text.replace('"', '\\"')
    js_code = f"""
    <script>
    function copyToClipboard_{copy_id}() {{
        const text = "{escaped_text}";
        navigator.clipboard.writeText(text).then(function() {{
            // Show success toast
            const toast = document.createElement('div');
            toast.style.cssText = `
                position: fixed;
                bottom: 20px;
                right: 20px;
                background: #1E3A5F;
                color: white;
                padding: 12px 24px;
                border-radius: 8px;
                box-shadow: 0 4px 12px rgba(0,0,0,0.15);
                z-index: 10000;
                font-size: 14px;
                animation: slideIn 0.3s ease;
            `;
            toast.textContent = "{success_message}";
            document.body.appendChild(toast);
            
            // Auto remove after 3 seconds
            setTimeout(function() {{
                toast.style.animation = 'slideOut 0.3s ease';
                setTimeout(function() {{
                    document.body.removeChild(toast);
                }}, 300);
            }}, 3000);
        }}, function(err) {{
            console.error('Failed to copy: ', err);
        }});
    }}
    
    // Add animations
    const style = document.createElement('style');
    style.textContent = `
        @keyframes slideIn {{
            from {{
                transform: translateX(100%);
                opacity: 0;
            }}
            to {{
                transform: translateX(0);
                opacity: 1;
            }}
        }}
        @keyframes slideOut {{
            from {{
                transform: translateX(0);
                opacity: 1;
            }}
            to {{
                transform: translateX(100%);
                opacity: 0;
            }}
        }}
    `;
    document.head.appendChild(style);
    
    copyToClipboard_{copy_id}();
    </script>
    """
    
    components.html(js_code, height=0)
    return True


def create_email_share_link(itinerary: str, destination: str, 
                            subject: str = None, body: str = None) -> str:
    """
    Create a mailto link for email sharing.
    
    Args:
        itinerary: The itinerary content
        destination: Travel destination
        subject: Email subject (optional)
        body: Email body (optional)
    
    Returns:
        mailto: URL for email client
    """
    if subject is None:
        subject = f"Travel Itinerary: {destination}"
    
    if body is None:
        body = f"Here's my travel itinerary for {destination}:\n\n{itinerary[:500]}...\n\nGenerated by Agentic Travel Itinerary Planner"
    
    # URL encode the content
    import urllib.parse
    encoded_subject = urllib.parse.quote(subject)
    encoded_body = urllib.parse.quote(body)
    
    return f"mailto:?subject={encoded_subject}&body={encoded_body}"


def generate_shareable_link(itinerary_data: Dict[str, Any], 
                            expires_in_hours: int = 24) -> str:
    """
    Generate a shareable link for the travel plan.
    
    Args:
        itinerary_data: The itinerary data to share
        expires_in_hours: Link expiration time in hours
    
    Returns:
        Shareable link URL
    """
    # Create a unique hash for this itinerary
    data_str = json.dumps(itinerary_data, sort_keys=True)
    link_hash = hashlib.sha256(data_str.encode()).hexdigest()[:16]
    
    # Calculate expiration
    expires_at = datetime.now() + timedelta(hours=expires_in_hours)
    
    # Store in session state for retrieval
    st.session_state[f"share_link_{link_hash}"] = {
        "data": itinerary_data,
        "expires_at": expires_at,
        "created_at": datetime.now()
    }
    
    # Return a simplified link (in production, this would be a real URL)
    # For demo purposes, we'll use a local storage approach
    return f"share://{link_hash}"


def get_cached_share_link(link_hash: str) -> Optional[Dict[str, Any]]:
    """
    Retrieve cached share link data.
    
    Args:
        link_hash: The hash identifier for the share link
    
    Returns:
        Cached data or None if expired/not found
    """
    key = f"share_link_{link_hash}"
    if key in st.session_state:
        entry = st.session_state[key]
        if datetime.now() < entry.get("expires_at", datetime.now()):
            return entry.get("data")
        else:
            # Expired, clean up
            del st.session_state[key]
    return None


def create_share_buttons(itinerary: str, destination: str, 
                         days: int, budget: float, currency: str) -> None:
    """
    Create share buttons UI component.
    
    Args:
        itinerary: The itinerary content
        destination: Travel destination
        days: Number of days
        budget: Total budget
        currency: Currency code
    """
    # Create share options container
    st.markdown("### Share This Itinerary")
    
    col1, col2, col3 = st.columns(3)
    
    with col1:
        # Copy to Clipboard
        if st.button("📋 Copy to Clipboard", use_container_width=True, key="copy_clipboard"):
            copy_to_clipboard(itinerary, "Itinerary copied to clipboard!")
            _track_share_event(destination, "copy", True)
    
    with col2:
        # Email Share
        email_link = create_email_share_link(itinerary, destination)
        st.markdown(f"""
        <a href="{email_link}" target="_blank" style="
            display: inline-block;
            width: 100%;
            padding: 0.5rem 1rem;
            background: linear-gradient(135deg, #1E3A5F 0%, #008080 100%);
            color: white;
            text-decoration: none;
            border-radius: 8px;
            font-weight: 500;
            text-align: center;
            transition: all 0.2s ease;
        " onmouseover="this.style.transform='translateY(-1px)'; this.style.boxShadow='0 4px 12px rgba(30,58,95,0.2)';" onmouseout="this.style.transform='translateY(0)'; this.style.boxShadow='none';">
            📧 Email Share
        </a>
        """, unsafe_allow_html=True)
        _track_share_event(destination, "email", True)
    
    with col3:
        # Share Link
        share_data = {
            "destination": destination,
            "days": days,
            "budget": budget,
            "currency": currency,
            "itinerary": itinerary,
            "generated_at": datetime.now().isoformat()
        }
        share_link = generate_shareable_link(share_data)
        
        if st.button("🔗 Share Link", use_container_width=True, key="share_link"):
            copy_to_clipboard(share_link, "Share link copied to clipboard!")
            _track_share_event(destination, "link", True)


def show_share_options(itinerary: str, destination: str,
                       days: int, budget: float, currency: str) -> None:
    """
    Display share options in a collapsible section.
    
    Args:
        itinerary: The itinerary content
        destination: Travel destination
        days: Number of days
        budget: Total budget
        currency: Currency code
    """
    with st.expander("📤 Share This Itinerary", expanded=False):
        create_share_buttons(itinerary, destination, days, budget, currency)
